[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }

dotenv = "0.15.0"

reqwest = { version = "0.12.9", features = ["blocking", "cookies"] }
futures-io = { version = "0.2.0-beta" }
